import json
import random
import os
from datetime import datetime

# Paths
DATA_DIR = os.path.join(os.path.dirname(__file__), 'data')
SOLUTIONS_FILE = os.path.join(DATA_DIR, 'solutions.json')
CRITERIA_FILE = os.path.join(DATA_DIR, 'criteria.json')
SCORES_FILE = os.path.join(DATA_DIR, 'scores.json')

def load_json(path):
    with open(path, 'r') as f:
        return json.load(f)

def save_json(path, data):
    with open(path, 'w') as f:
        json.dump(data, f, indent=2)

def main():
    print(f"Reading data from {DATA_DIR}...")
    solutions = load_json(SOLUTIONS_FILE)
    criteria = load_json(CRITERIA_FILE)

    new_scores = []
    
    print(f"Generating scores for {len(solutions)} solutions and {len(criteria)} criteria...")

    for sol in solutions:
        # Create a "personality" for each solution to make them distinct
        # Some might be strong in Detection (DP), others in Response (RA)
        bias = {
            'DP': random.choice([0, 1, -1]),
            'RA': random.choice([0, 1, -1]),
            'IE': random.choice([0, 1, -1]),
            'PS': random.choice([0, 1, -1]),
            'DU': random.choice([0, 1, -1]),
            'RC': random.choice([0, 1, -1])
        }

        items = []
        for crit in criteria:
            # Get category prefix
            cat_prefix = crit['id'].split('-')[0]
            
            # Base random score 2-5 (avoiding 1s to make them look competitive)
            score = random.randint(2, 5)
            
            # Apply bias
            if cat_prefix in bias:
                score += bias[cat_prefix]
            
            # Clamp to 1-5
            score = max(1, min(5, score))

            items.append({
                "criterionId": crit['id'],
                "evidence": "Generated by Randomizer for Battle testing.",
                "mode": "Simulation",
                "score": score
            })

        new_scores.append({
            "solutionId": sol['id'],
            "timestamp": datetime.now().isoformat(),
            "items": items
        })

    print(f"Saving {len(new_scores)} score records to {SCORES_FILE}...")
    save_json(SCORES_FILE, new_scores)
    print("Done!")

if __name__ == '__main__':
    main()
